FROM jupyter/datascience-notebook:python-3.7.6
LABEL maintainer="Zhiao Shi <zhiao.shi@gmail.com>"
LABEL description="neoflow variant annotation"
LABEL version="1.0.0"

COPY variant_annotation.py /usr/local/bin
CMD ["/bin/bash"]
